//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountAccess
    {
        public int accessID { get; set; }
        public int acctNo { get; set; }
        public int acctManagers { get; set; }
        public int acctAccountant { get; set; }
    }
}
