//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accountsTable()
        {
            this.ledgerTables = new HashSet<ledgerTable>();
            this.requestTables = new HashSet<requestTable>();
            this.transactionEntryTables = new HashSet<transactionEntryTable>();
        }
    
        public int acctNo { get; set; }
        public string acctName { get; set; }
        public int acctCat { get; set; }
        public int acctSubCat { get; set; }
        public decimal totalDebits { get; set; }
        public decimal totalCredits { get; set; }
        public decimal balance { get; set; }
        public decimal initialBalace { get; set; }
        public Nullable<int> acctTerm { get; set; }
        public Nullable<int> createdBy { get; set; }
        public string comments { get; set; }
        public Nullable<int> editedBy { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public byte[] dateEdited { get; set; }
        public Nullable<int> acctStateID { get; set; }
    
        public virtual accountCategoryTable accountCategoryTable { get; set; }
        public virtual accountSubCategoryTable accountSubCategoryTable { get; set; }
        public virtual accountStateTable accountStateTable { get; set; }
        public virtual accountTermTable accountTermTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ledgerTable> ledgerTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requestTable> requestTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transactionEntryTable> transactionEntryTables { get; set; }
    }
}
