//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachTable
    {
        public int attachID { get; set; }
        public int journalID { get; set; }
        public string attachLocation { get; set; }
        public byte[] attachContents { get; set; }
    
        public virtual journalTable journalTable { get; set; }
    }
}
