//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BT_Entity1 : DbContext
    {
        public BT_Entity1()
            : base("name=BT_Entity1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountAccess> accountAccesses { get; set; }
        public virtual DbSet<accountCategoryTable> accountCategoryTables { get; set; }
        public virtual DbSet<accountsTable> accountsTables { get; set; }
        public virtual DbSet<accountStateTable> accountStateTables { get; set; }
        public virtual DbSet<accountSubCategoryTable> accountSubCategoryTables { get; set; }
        public virtual DbSet<accountTermTable> accountTermTables { get; set; }
        public virtual DbSet<attachTable> attachTables { get; set; }
        public virtual DbSet<eventLog> eventLogs { get; set; }
        public virtual DbSet<journalTable> journalTables { get; set; }
        public virtual DbSet<journalTypesTable> journalTypesTables { get; set; }
        public virtual DbSet<ledgerTable> ledgerTables { get; set; }
        public virtual DbSet<passwordTable> passwordTables { get; set; }
        public virtual DbSet<requestTable> requestTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<transactionEntryTable> transactionEntryTables { get; set; }
        public virtual DbSet<transactionStatusTable> transactionStatusTables { get; set; }
        public virtual DbSet<transactionTypeTable> transactionTypeTables { get; set; }
        public virtual DbSet<userRoleTable> userRoleTables { get; set; }
        public virtual DbSet<userStateTable> userStateTables { get; set; }
        public virtual DbSet<userTable> userTables { get; set; }
    }
}
