//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventLog
    {
        public int eventID { get; set; }
        public byte[] eventTimeDate { get; set; }
        public Nullable<int> userID { get; set; }
        public string fromPage { get; set; }
        public string toPage { get; set; }
        public Nullable<int> journalID { get; set; }
        public Nullable<int> transactionID { get; set; }
        public Nullable<int> attachID { get; set; }
        public Nullable<int> ledgerID { get; set; }
        public Nullable<int> userID2 { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
    }
}
