//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledgerTable
    {
        public int ledgerID { get; set; }
        public int journalID { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public int acctNo { get; set; }
        public decimal balance { get; set; }
        public Nullable<decimal> debits { get; set; }
        public Nullable<decimal> credits { get; set; }
        public Nullable<int> lStatus { get; set; }
    
        public virtual accountsTable accountsTable { get; set; }
        public virtual journalTable journalTable { get; set; }
    }
}
