//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passwordTable
    {
        public int passID { get; set; }
        public int userID { get; set; }
        public string currentPass { get; set; }
        public string password2 { get; set; }
        public string password3 { get; set; }
        public string password4 { get; set; }
        public string password5 { get; set; }
        public string resetPasswordCode { get; set; }
    
        public virtual userTable userTable { get; set; }
    }
}
