//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestTable
    {
        public int requestID { get; set; }
        public Nullable<int> requestAcct { get; set; }
        public string request { get; set; }
        public string requestStatus { get; set; }
        public Nullable<int> requestedBy { get; set; }
        public Nullable<int> requestFilledBy { get; set; }
    
        public virtual accountsTable accountsTable { get; set; }
    }
}
