//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionEntryTable
    {
        public int transactionID { get; set; }
        public int transactionType { get; set; }
        public decimal transactionAmount { get; set; }
        public int acctNo { get; set; }
        public int journalID { get; set; }
    
        public virtual accountsTable accountsTable { get; set; }
        public virtual journalTable journalTable { get; set; }
        public virtual transactionTypeTable transactionTypeTable { get; set; }
    }
}
