//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userTable()
        {
            this.journalTables = new HashSet<journalTable>();
            this.journalTables1 = new HashSet<journalTable>();
            this.passwordTables = new HashSet<passwordTable>();
        }
    
        public int userID { get; set; }
        public string userName { get; set; }
        public int userRoleID { get; set; }
        public int userStateID { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public byte[] lastUpdated { get; set; }
        public string userFName { get; set; }
        public string userLName { get; set; }
        public string userPhone { get; set; }
        public string userEMail { get; set; }
        public string userPassword { get; set; }
        public string resetPasswordCode { get; set; }
        public int createdBy { get; set; }
        public int editedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<journalTable> journalTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<journalTable> journalTables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<passwordTable> passwordTables { get; set; }
        public virtual userRoleTable userRoleTable { get; set; }
        public virtual userStateTable userStateTable { get; set; }
    }
}
